export const chats = [
  {
    id: 1,
    name: 'Alice Johnson',
    message: 'Masih ready gan?',
    vendor: 'tokopedia',
    storeName: 'Beauty Lovers',
    unreadCount: 1,
    userId: 1,
    date: '2025-02-26',
  },
  {
    id: 2,
    name: 'Bob Smith',
    message: 'Kapan dikirim?',
    vendor: 'shopee',
    storeName: 'Beauty Lovers',
    unreadCount: 2,
    userId: 2,
    date: '2025-02-26',
  },
  {
    id: 3,
    name: 'Charlie Brown',
    message: 'Ada diskon gak?',
    vendor: 'tokopedia',
    storeName: 'Beauty Lovers',
    unreadCount: 0,
    userId: 3,
    date: '2025-02-23',
  },
  {
    id: 4,
    name: 'Diana Prince',
    message: 'cara return produk gmn?',
    vendor: 'shopee',
    storeName: 'Beauty Lovers',
    unreadCount: 3,
    userId: 4,
    date: '2025-02-26',
  },
  {
    id: 5,
    name: 'Ethan Hunt',
    message: 'tahan lama ga nih?',
    vendor: 'shopee',
    storeName: 'Beauty Lovers',
    unreadCount: 0,
    userId: 5,
    date: '2025-02-25',
  },
  {
    id: 6,
    name: 'Fiona Green',
    message: 'gmn cara pengiriman?',
    vendor: 'tokopedia',
    storeName: 'Beauty Lovers',
    unreadCount: 5,
    userId: 6,
    date: '2025-02-26',
  },
  {
    id: 7,
    name: 'Gina Rodriguez',
    message: 'gmn cara bayar nya?',
    vendor: 'tokopedia',
    storeName: 'Beauty Lovers',
    unreadCount: 0,
    userId: 7,
    date: '2025-02-24',
  },
];
